### ISSUE TITLE
Use a good default iteration count

### ISSUE THREAD

**Issue by dlongley** [digitalbazaar/did-io#2]
Use this as a guideline for determining a good default PBE iteration count:

http://security.stackexchange.com/questions/3959/recommended-of-iterations-when-using-pkbdf2-sha256

> You should use the maximum number of rounds which is tolerable,
> performance-wise, in your application. The number of rounds is a slowdown factor,
> which you use on the basis that under normal usage conditions, such a slowdown
> has negligible impact for you (the user will not see it, the extra CPU cost does not
> imply buying a bigger server, and so on). This heavily depends on the operational
> context: what machines are involved, how many user authentications per second...
> so there is no one-size-fits-all response.
> 
> The wide picture goes thus:
> - The time to verify a single password is v on your system. You can adjust this time
>   by selecting the number of rounds in PBKDF2. A potential attacker can gather f times
>   more CPU power than you (e.g. you have a single server, and the attacker has 100
>   big PC, each being twice faster than your server: this leads to f=200).
> - The average user has a password of entropy n bits (this means that trying to guess
>   a user password, with a dictionary of "plausible passwords", will take on
>   average 2n-1 tries).
> - The attacker will find your system worth attacking if the average password can be
>   cracked in time less than p (that's the attacker's "patience").
> 
> Your goal is to make the average cost to break a single password exceed the
> attacker patience, so that he does not even tries to, and goes on to concentrate
> on another, easier target.
> 
> ...
> 
> So the remaining parameter is v. **With f = 200 (an attacker with a dozen good
> GPU), a patience of one month, and n = 32, _you need v to be at least 8 milliseconds_**.
> So you should set the number of rounds in PBKDF2 such that computing it over a
> single password takes at least that much time on your server. You will still be able
> to verify 120 passwords per second with a single core, so the CPU impact should
> be negligible for you. Actually, it is safer to use more rounds than that, because,
> let's face it, getting 32 bits worth of entropy out of the average user password is a
> bit optimistic.

So if we think a month is enough to deter an attacker with a dozen good GPUs, our time to generate a key should be at least 8ms. We can easily go higher than this without messing up the UX and should. We just need to consider different browsers and CPUs will be running this.

We may also want to randomize the number of iterations, with a certain required minimum.

**Comment by dmitrizagidulin** [comment]
n/a, closing.
