### ISSUE TITLE
Can bad things happen in the `default` case

### ISSUE THREAD

**Issue by mattcollier** [digitalbazaar/did-io#22]
https://github.com/digitalbazaar/did-io/blob/b850abb95d6232be307537bd9a6351c6a9238a87/lib/ld-key-pair.js#L60

It appears to me that some there could be some unintended consequences from having this default case.  This module really only supports two key types, is that correct?  I think we just be explicit about that and throw if the keyType is not one of the acceptable types.

I would add that I think the use of `switch` with a fall through to a default case is a pattern to be avoided.  I think there is good reasoning behind DB's strong preference for if...return pattern whenever possible.  if...else when it's absolutely necessary.  I just did a quick search and it appears that `switch` is used in only one place in the entire bedrock backend code base.

**Comment by dmitrizagidulin** [comment]
Thanks @mattcollier, good point. I'll change it to throw an error in the default (unrecognized) case.

**Comment by dmitrizagidulin** [comment]
Fixed by #23, closing.
