### ISSUE TITLE
Allow for calling generate API with no arguments

### ISSUE THREAD

**Issue by mattcollier** [digitalbazaar/did-io#36]
https://github.com/digitalbazaar/did-io/blob/development/lib/methods/veres-one/veres-one.js#L131-L132

Please add `= {}` here to allow for doing `v1.generate()` to generate using defaults.

**Comment by dmitrizagidulin** [comment]
:+1:

**Comment by dmitrizagidulin** [comment]
Implemented in #37, closing.
