### ISSUE TITLE
Where should `attachInvocationProof` live?

### ISSUE THREAD

**Issue by mattcollier** [digitalbazaar/did-io#42]
@dlongley @dmitrizagidulin 

https://github.com/digitalbazaar/did-io/blob/899de8edd4e2c9f70f16ede7a39d24f2cce495b0/lib/methods/veres-one/veres-one.js#L335-L359

Do we need it at all?

Should it be part of crypto-ld?

If we need the wrapper, we know that we want to be able to add these sorts of proofs to operations other that DID Documents.

**Comment by dmitrizagidulin** [comment]
I'm also curious what the "validate private key" comment in the TODO means. What would it be validated against?

**Comment by dmitrizagidulin** [comment]
The veres one driver has now been moved to https://github.com/veres-one/did-veres-one, so closing this issue.
