### ISSUE TITLE
did-key… links return 404

### ISSUE THREAD

**Issue by sebilasse** [digitalbazaar/did-io#54]
The links to `did-key` and `did-key-driver` do not work. 
Shouldn't they link to https://github.com/digitalbazaar/did-method-key-js ?

**Comment by aljones15** [comment]
The non-working links are incorrect. I do think you are correct about your link. However the spec for did-method-key I believe was moved here: 

https://github.com/w3c-ccg/did-method-key

while the actual library is here:
https://github.com/digitalbazaar/did-method-key-js

@dmitrizagidulin if you have a moment to clarify this.

I'm not sure if the links should be pointing at the library or the spec.

just another note: any link to `https://github.com/digitalbazaar/did-io/blob/master` or to `https://w3c-ccg.github.io/didm-veres-one/` in the README is broken. It looks like the `did-key` links should be the spec and the `did-key-driver` is the library, but I'm not an expert on this one.

**Comment by dmitrizagidulin** [comment]
Fixed, closing.
